Upgrade to JMeter 5.4.1
hellofresh/kangal-jmeter pull request #15
Opened 2021-05-14 19:11 UTC by thiagoarrais

This PR updates to latest available JMeter (5.4.1). It also upgrades the Java Runtime Environment (to 11).

I also took the liberty to change how the JMeter install location is referenced to make future upgrades easier.

2021-05-25 10:23 UTC, lopb submitted a review, later dismissed
seems legit!

2021-05-25 10:25 UTC, lopb commented
This pull request will be very useful.

2021-05-25 12:09 UTC, diegomarangoni commented
hey @thiagoarrais, thanks for the contribution, we will review it internally.

maybe would be better to add version tags before merging this

wdyt @s-radyuk @s4nji ?

2021-05-25 12:12 UTC, ldeitos requested changes

2021-05-25 12:12 UTC, ldeitos commented on docker/jmeter-master/launcher.sh
> +  $JMETER_HOME/bin/jmeter.sh -n -t "$FILE" -l results.csv -e -o /results/ -Jserver.rmi.ssl.disable="$SSL_DISABLED" "$WORKER_OPTS" >>output.log 2>&1 &
@thiagoarrais, adicione " na variável para passar no lint: "$JMETER_HOME"

2021-05-25 12:12 UTC, diegomarangoni reviewed
meanwhile, can you fix the linting, please?

2021-05-25 12:12 UTC, diegomarangoni commented on docker/jmeter-master/launcher.sh
> +  $JMETER_HOME/bin/jmeter.sh -n -t "$FILE" -l results.csv -e -o /results/ -Jserver.rmi.ssl.disable="$SSL_DISABLED" "$WORKER_OPTS" >>output.log 2>&1 &
```suggestion
  "$JMETER_HOME"/bin/jmeter.sh -n -t "$FILE" -l results.csv -e -o /results/ -Jserver.rmi.ssl.disable="$SSL_DISABLED" "$WORKER_OPTS" >>output.log 2>&1 &
```
ShellCheck linting is complaining about unquoted env var

2021-05-25 12:30 UTC, ldeitos reviewed
LGTM. I think that MR will be useful to make easier upgrade JMeter Version.

2021-05-27 10:03 UTC, s4nji approved these changes

2021-05-27 10:14 UTC, s4nji approved these changes

2021-05-27 10:15 UTC, diegomarangoni approved these changes

2021-05-27 10:18 UTC, s4nji approved these changes

2021-05-27 10:19 UTC, s4nji approved these changes

2021-05-27 10:20 UTC, diegomarangoni approved these changes

2021-05-27 10:30 UTC, diegomarangoni commented
hey @ldeitos, as you request some changes on this PR we need your approval here to be able to merge

2021-05-27 13:35 UTC, ldeitos approved these changes
lgtm

2021-05-27 13:35 UTC, merged

2021-05-27 13:35 UTC, s4nji commented
Thank you!